### ISSUE TITLE
Date picker 1.13.1

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#14]
There is an issue with the date picker in 1.13.1
In the "Inventory" and "Purchase" the date picker is not working. The Icon is also not aligned correctly.

**Comment by berrnd** [comment]
The border problem is fixed, now looks like this:

![2018-07-13_21-38-55](https://user-images.githubusercontent.com/2161815/42710679-3d27532e-86e5-11e8-9b49-f2f4547bdc41.gif)

**Comment by BlizzWave** [comment]
Deleted everything (instead of overwriting).
Looks better, but not perfect.

Also is there a way of setting start of the week as monday and not sunday?

![datop](https://user-images.githubusercontent.com/6298655/42722802-ef8e5b4e-8752-11e8-96fe-3eaa5a5ba488.png)

**Comment by berrnd** [comment]
Ok, then this was the problem - the width problem is fixed in the next release as mentioned above, or grab and replace [grocy.css from master branch](https://raw.githubusercontent.com/berrnd/grocy/master/public/css/grocy.css) manually if you want to test it now.

The localization of the calendar comes from Moment.js, for German the first day of the week is also monday - you have to set [this translation item](https://github.com/berrnd/grocy/blob/aa0771877ff9010a05a642b6b0ce115dfe00ab84/localization/de.php#L156) to a available Moment.js localization file name (should be just `nl ` I think...).

**Comment by BlizzWave** [comment]
Had to update datetimepicker.blade.php with the one from your source.

Had to add "'additionalCssClasses' => 'date-only-datetimepicker'"
to purchase.blade.php and inventory.blade.php also. 

Adding "nb" to the translation file it showes the correct format in the calendar. 
I was using "no", haha. 

But this will be fixed in your next release. So consider this "bug" fixed.

**Comment by berrnd** [comment]
Would be cool if could share (create a pull request) your translation. (?) :)

There will be a new release with all the small UI improvements and one big new feature - Recipes (auto check if everything is in stock for a recipe, put the missing things on the shopping list, and so on)...

**Comment by BlizzWave** [comment]
Sure I can do that. Just need to figure out the correct way of translating everything. I have been going back and forth about how something should be translated without it sounding stupid. 

Thought you said you did not have time to work on grocy that much?!?
Haha.

Keep up the great work!
