### ISSUE TITLE
Issue: Recipes can only use quantity units for amount needed

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#32]
When adding a new recipe to grocy you are only allowed to use quantity units. 
So for example, making a cake:
Ingredients required is 250 grams of flour. But the quantity unit might be a pack. 

I'm not really sure how we would accomplish this.
Maybe let grocy just see if you have the products in stock and just ignore quantity units?

**Comment by berrnd** [comment]
I'm also not sure about this, that's why I also don't added a "consume all ingredients" button (to consume all products needed by a recipe with one click) in the first stage...

The base idea was to keep it simpel, there is only one single quantity unit per product, only for purchasing there can be a different one and it is converted to the "stock unit" directly on booking the purchase. Stock quantity can also only be an integral number (no decimals), as this would lead to rounding problems at some point.

The rest is just organization, I think. I personally for example don't track every roll of toilet paper, I just have packs and "consume" one when opening the next pack. So in general I have products of which I track every unit, others which I track when I throw the wrapping away / opening the next unit.

So yes, should be something like you mentioned.
Maybe a checkbox next to the amount when adding a recipe ingredient named "Just ensure that at least one unit is in stock". A "consume recipe" button would then just ignore those ingredients.

**Comment by BlizzWave** [comment]
Have you given this some more thought?

**Comment by berrnd** [comment]
Will implement it as discussed here above, just haven't had the time yet...

**Comment by berrnd** [comment]
This is now done, maybe you can have a short look about this on the [already updated english demo](https://demo-en.grocy.info) and let me know if you find anything to make different/better...

Demo recipe to showcase this is "Pancakes" - flour/sugar is in stock in packs, but in the recipe there are 200 grams needed...

**Comment by BlizzWave** [comment]
Looks good Bernd. 
I was wondering if it would understand what to do if you need 200 gram of flour. Because in my instance the normal QU for flour is 1 kg.
You had made it smart enough to add one QU.

So from my point of view this is working and can be closed.

**Comment by BlizzWave** [comment]
Awesome!
