### ISSUE TITLE
Feature Request: Mini thumbnail picture of item if you click and hold

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#58]
A small little thumbnail picture if you click and hold on item in stock overview page.
Would need to be very strict about picture size. Lets say 120x120, no more no less to keep load down.

Picture attached is 120x120. 

![cucumber1-120x120](https://user-images.githubusercontent.com/6298655/45926806-a6a18380-bf28-11e8-913f-33888c490ae4.jpg)

**Comment by cavebeat** [comment]
I'll second this. To have a basic image of the item.

**Comment by berrnd** [comment]
If someone wants to try in the [pre-release demo](https://demo-prerelease.grocy.info):
- A picture can be uploaded on the product edit screen
- On the stock overview page there is a new button next to consume which shows the picture of the product (only enabled when the product has a picture)

No demo data so far, I uploaded the picture above for product "Cucumber".

Still needs some polish, that's the first time we handle files, so also security things, file size checks, and so on (please don't overload my demo server :D).

The files are saved in `data/storage/productpictures`.

**Comment by BlizzWave** [comment]
Does not like long file names. Gives you the error of maybe duplicate.
But I don't consider this a bug. Just a thing to note. 
Maybe more accurate error messages?

**Comment by berrnd** [comment]
Changes since yesterday:

- Better file name validation
- Finished product edit page (added also possibility to remove a picture)
- On the stock overview page there is no separate button to show the picture, instead a little image icon next to the product name apperas and the whole name cell is clickable to show the picture, if the product has one
- The picture is also shown in the productcard (purchase/consume/etc. pages)

To workaround duplicate file names, just some random characters are prepended to the file name during the upload - I think that should be enough...

Let me know if you find any bugs or have any further/other ideas on this. :)

**Comment by BlizzWave** [comment]
Put picture in the center maybe?

![capture](https://user-images.githubusercontent.com/6298655/46308207-5924b680-c5b9-11e8-8609-1807ba0d3fa7.JPG)

**Comment by berrnd** [comment]
Sure ... I'm happy when the rest seems to work... :)

Maybe I'm just a little worried about the (security) of the [file upload API](https://demo-prerelease.grocy.info/api#/Files)...
- Should not be possible to serve file from outside the `data/storage` directory (should already be fine because `/` is disallowed in the requested file name)
- The file is handled on both server and client side completely in RAM, no chunking or something and also no file size checks (only configured limits from PHP or the webserver will apply)
  - => So means is only good for small files as of now, so for product pictures it will be ok I think...

**Comment by berrnd** [comment]
I added a button in the dialog to jump to the product edit screen (and back on saving the product)...
Centering the title I did not get to work...

**Comment by berrnd** [comment]
Thanks, yes that would affect every modal/dialog - I limited it to that one in https://github.com/berrnd/grocy/commit/ae58606d04f90be687b00ee1fb23fe3fc71ac116.

**Comment by BlizzWave** [comment]
Something to note about the picture upload feature. It will accept any file. Not sure about the file size, but tried 25mb and that worked fine.

**Comment by berrnd** [comment]
The file API accepts all file types, but preselcting only image files in the file picker is possible - done in https://github.com/berrnd/grocy/commit/f90faca62ee0a3b346cb1b7f51d8722971313edf.

**Comment by BlizzWave** [comment]
I have a small addition to this. When editing products it would be useful with a small icon that shows if the product actually has a picture or not. 

Please have a look at my example. 

![examlple](https://user-images.githubusercontent.com/6298655/46571533-e92a7d80-c976-11e8-8f64-e3621070adec.jpg)
