### ISSUE TITLE
Feature Request:  Stock with MHD/Shelf Life/Best Before Date for FIFO

### ISSUE THREAD

**Issue by cavebeat** [berrnd/grocy#61]
For example: I have posted goods receipt (purchased) 2kg of Flour with BestBeforeDate of 01.06.2019 and also 4 kg of Flour with BestBeforeDate of 01.06.2022. So i can rotate them with FIFO and use the oldest one. (assumed the first one is the piece with the lowest remaining shelf life)

So i have now 6 kg of Flour. Both BestBefore Date are now mixed together and the information is lost. Which one to pick for FIFO is now hard. 

https://de.wikipedia.org/wiki/Quant_(Wirtschaft) <-- If a stock is having the same characteristics, it should merge. If not it should be a second stock item with a different BestBeforeDate of the same product. 

At the moment i rotate my stock, for examples dried lentils and atm with grocy i'd never know if 99% or just 1% of the stock will be expired tomorrow.

**Comment by BlizzWave** [comment]
If I remember correctly this is on Bernd's To-Do list.

**Comment by berrnd** [comment]
(Yes, I should finally document all the already-on-my-to-do-list-points here as issues.)

What I want to add is that we are able to pick a specific stock item on consume.
Currently the fixed rule is "First expiring first, then FIFO" (see [here](https://github.com/berrnd/grocy/blob/60d47bef8413493cede072497479a3d8f9c5ce0a/services/StockService.php#L132)).

For your example I would suggest to just have packs of flour as a product in grocy, regardless if you buy it in 2 kg or 4 kg bundles. If that's important, maybe create 2 separate products. In the first case, you would have 2 packs of the same item flour in stock and the first one will be picked on consume, because it expires first. In the second case you would have 2 different products with an amount of 1 each in stock.

My main goal is to keep especially the "stock topic" as simple as possible.
(I'm working professionally for an ERP software which of course has all these things, also thought I just use that one some time ago before grocy, but all that things are too bloated for my kitchen... :D)

**Comment by berrnd** [comment]
I'll close this for now, feel free to come back on this if you have any further suggestions/questions on this...
