### ISSUE TITLE
Bug: Unable to consume from search results

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#66]
If you search for an item and then try and consume the result it won't let you.

![grocy_issue3](https://user-images.githubusercontent.com/6298655/46007756-252e2a80-c0bb-11e8-8c1b-60e62ecdf6e0.gif)

**Comment by berrnd** [comment]
Maybe has to to something with #51 - the tooltip overlaps the button in that example, so the button cannot be clicked...

**Comment by berrnd** [comment]
Tried a next attempt to fix the tooltip flickering problems, maybe you can check the [pre-release demo](https://demo-prerelease.grocy.info) for a quick test.

**Comment by BlizzWave** [comment]
Confirmed to be working on computer and tablet. :-)

**Comment by berrnd** [comment]
Thanks for testing, closing this and continuing on the "tooltip on mobile problem" in #67.

**Comment by berrnd** [comment]
I just disabled tooltips for now for touch input devices (#67).

**Comment by sleeplessnight2** [comment]
I have a better suggestion:

Instead of just dropping thoughtfully created tips, you could customize how tooltips are handled on a touch input.

Fortunately, hovering on touch inputs is a commonly known "designer" problem and a very good solution has been written down here: [https://uxmovement.com/mobile/how-to-display-tooltips-on-mobile-forms/](https://uxmovement.com/mobile/how-to-display-tooltips-on-mobile-forms/)

Would this be an option you would include or have someone else include?
