### ISSUE TITLE
Tooltips stay when using touch input

### ISSUE THREAD

**Issue by berrnd** [berrnd/grocy#67]
References also #66

Maybe use native tooltips again (they are not bad, Bootstrap/Popper.js tooltips are just nicer) or just disable them on touch input devices (they can also not or only hardly be triggered without being able to hover the element)...

**Comment by sleeplessnight2** [comment]
I have a better suggestion:

Instead of just dropping thoughtfully created tips, you could customize how tooltips are handled on a touch input.

Fortunately, "hover" on touch inputs is a commonly known "designer" problem and a very good solution has been written down here: https://uxmovement.com/mobile/how-to-display-tooltips-on-mobile-forms/

Would this be an option you would include or have someone else include?

**Comment by berrnd** [comment]
This here was about that tolltips could not be dismissed on mobile, not about that the position is "wrong" - so (again, sorry) dein Vergleich passt mal wieder nicht...

Wenn die Position also deiner Meinung nach im Eingabefeld besser ist statt neben der Bezeichnung - kannst es gerne (wohl per CSS) überall entsprechend hin basteln, mich störts nicht und ganz viele andere Anwendungen machen das genauso.

Wenns um das Problem geht, dass die Tooltips auf touch-input-devices nicht verschwinden:
Die Tooltips sind nicht selbst gebastelt, sondern die aus [Bootstrap](https://getbootstrap.com/docs/4.1/components/tooltips/) und die wiederum benutzen [Popper.js](https://popper.js.org/) - da müsste also man dann vermutlich mal eher gucken...

**Comment by sleeplessnight2** [comment]
Wow, how half the text is missing at my previous post ... 
I had previously something additional, important in the post inside and remained the design part.

It's not primarily about the design at all. That would be a nice side effect.

It's about the fact, that the problem of tooltips staying on the screen is caused by the fact, that there is no "hover" on a touchinput. So the named javascript function "mouse over", which is active on all tooltips.
This does not work on a touch system, which is why this "bug" was opened.

The problem is known to all webdesigners, so an alternative to the hover is needed. Often one goes the way to tap-and-hold or longpress.
This alternative goes among other things with the design, so that one can still tap the tooltip...

And there I wanted to ask, whether a rebuild of the handling of the tips would be a option instead of just disable, so that the valuable information are not simply gone?
