### ISSUE TITLE
Feature Request: Nested recipes

### ISSUE THREAD

**Issue by BlizzWave** [berrnd/grocy#77]
I have a little challenge with adding some recipes because some have small mini recipes in them. 
There can be multiple of the same thing in different quantities.

If you look at the example recipe here:

[https://tasty.co/recipe/sweet-and-sour-pork](url)

It mentions corn flour twice and oil

**Comment by BlizzWave** [comment]
Yeah, nested is the correct way of describing what I want. Hehe.

I'm aware that you can add the same twice, but it gets confusing even with the note

**Comment by BlizzWave** [comment]
Roughly how I thought about this.
Or maybe completly different tables for each nested portion of recipe


![capturefix](https://user-images.githubusercontent.com/6298655/46423548-17ba1580-c737-11e8-98c8-1e5ea1260ed8.jpg)

**Comment by berrnd** [comment]
Looks good, a little bit more difficult will be to add that in all the "how much in stock for that recipe" logic ... needs to be a recursive thing, because recipes can include other recipes which can also include other recipes (and multiple ones, I think)...

**Comment by berrnd** [comment]
(More or less a note to myself to remember when starting working on this:)

Had some thoughts on this, won't be that difficult at all from the logic side - execept the following:

Currently the "is in stock logic" is done by the SQL view `recipes_fulfillment` per recipe position.
If a whole recipe is in stock or not is then a "group by recipe" over that view (done in a second view `recipes_fulfillment_sum`).
So when two recipes contain 1 QU of the same ingredient each, but there is only 1 QU in stock, both is considered as "is in stock", because the comparison is done on position level.
To solve this, some kind of "virtual stock" would be needed which is reduced per position while comparing what is in stock for a recipe.
And that's also already the case for that example when the ingredient is in a single recipe twice.

**Comment by berrnd** [comment]
A first version for this is ready, I think. :)

Maybe you can play around a little bit in the [pre-release demo](https://demo-prerelease.grocy.info/) and let me know what you think or if you find any problems, showcase recipe is [this](https://demo-prerelease.grocy.info/recipe/6) one.

The problem mentioned by myself above _"when two recipes contain 1 QU of the same ingredient each, but there is only 1 QU in stock, and these two recipes are nested into another one, both ingredients are considered as "is in stock" for that recipe, because the comparison is done on recipe position level"_ is still true.
Unfortunately this is not so easy to do in the current implementation because all the "core recipe logic" is done as a single database query, would need to redo this completely...

**Comment by BlizzWave** [comment]
Well I don't want to be Mr negative here, but that doesn't really work.

For example if I'm to use my example recipe (tasty link) I would have to add "deep frying" and "sauce" as a recipe. 

Also as you mention in the end. The recipe function might need to be rebuilt.

**Comment by berrnd** [comment]
> Well I don't want to be Mr negative here, but that doesn't really work.

Absolutely no problem, different views are good to keep the progress...

> For example if I'm to use my example recipe (tasty link) I would have to add "deep frying" and "sauce" as a recipe.

So maybe I understood that wrong, when I look again at your example recipe above, it's maybe more like you want to group some ingredients together in the same single recipe, to just have headlines per "group" at the end, right?

**Comment by berrnd** [comment]
Just to make clear what I meant then: https://demo-prerelease.grocy.info/recipes?recipe=1&row=3

(With just this, there is no problem about the "in stock logic" because with that recipes are not nested...)

![firefox_2018-10-25_22-49-45](https://user-images.githubusercontent.com/2161815/47529504-4e073280-d8a8-11e8-9a2b-7f0611d69a8a.png)

**Comment by BlizzWave** [comment]
Oh!! I just saw the "pancakes / chocolate".
The pizza recipe is pretty much exactly what I ment. Sorry about that.
